#!/bin/bash
# Usage: gentest [args] <input>.gx
#
# Where:
#   [args] are arguments for conv-gcode.py
#   <input>.gx is the FlashPrint generated gx file to process
#   <input>_<args>.gx will be the generated output file.
#
# This will generate a test output gx file from the FlashPrint gx file and
# show stats. The output file will have the <args> encoded onto the end of
# the filename.

infile="${@:$#}"
argstr=$(echo "${@:1:$#-1}" | sed -e 's:[- =.]::g')

# Start with outfile matching infile.
outfile="${infile}"

# Strip any existing conv-gcode.py args from the name.
if [[ "${outfile}" =~ .*_(Te|Tp|Fe|Fc|Kf|Kb)[0-9].*\.gx? ]]; then
  outfile="${outfile%_*}.${outfile##*.}"
fi

# Add the new conv-gcode.py args from the name.
outfile="${outfile%.*}_${argstr}.${outfile##*.}"

echo "Processing '${infile}' into '${outfile}'."
./conv-gcode.py "$@" > "$outfile" &&
git sdiff --no-index -a "$infile" "$outfile"

#./gxsum $outfile
